In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
train_data = pd.read_csv('kc_house_train_data.csv')

In [4]:
test_data = pd.read_csv('kc_house_test_data.csv')

In [5]:
train_data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

## Adding 4 new Variables to train and test data

‘bedrooms_squared’ = ‘bedrooms’*‘bedrooms’
‘bed_bath_rooms’ = ‘bedrooms’*‘bathrooms’
‘log_sqft_living’ = log(‘sqft_living’)
‘lat_plus_long’ = ‘lat’ + ‘long’

In [6]:
temp = train_data

In [7]:
def add_columns(data):
    data['bedrooms_squared'] = data['bedrooms'] * data['bedrooms']
    data['bed_bath_rooms'] = data['bedrooms'] * data['bathrooms']
    data['log_sqft_living'] = np.log(data['sqft_living'])
    data['lat_plus_long'] = data['lat'] + data['long']

In [8]:
list(map(add_columns, (train_data, test_data)))

[None, None]

In [9]:
train_data[['bedrooms_squared', 'bed_bath_rooms', 'log_sqft_living', 'lat_plus_long']]

       bedrooms_squared  bed_bath_rooms  log_sqft_living  lat_plus_long
0                     9            3.00         7.073270       -74.7458
1                     9            6.75         7.851661       -74.5980
2                     4            2.00         6.646391       -74.4951
3                    16           12.00         7.580700       -74.8722
4                     9            6.00         7.426549       -74.4282
5                    16           18.00         8.597851       -74.3489
6                     9            6.75         7.447168       -75.0173
7                     9            4.50         6.966024       -74.9055
8                     9            3.00         7.484369       -74.8247
9                     9            7.50         7.544332       -74.6626
10                    9            7.50         8.177516       -74.5443
11                    4            2.00         7.056175       -74.6020
12                    9            5.25         7.222566       -74.4323
13                   25           10.00         7.501082       -74.7240
14                    9            6.00         7.544332       -74.2343
15                   16            4.00         7.377759       -74.6782
16                    4            2.00         7.090077       -74.9011
17                    9            3.00         7.130899       -74.9717
18                   16            7.00         7.390181       -74.6385
19                    9            8.25         8.022897       -74.7014
20                   25           12.50         7.727535       -74.8424
21                    4            3.00         6.975414       -74.8127
22                    9            6.75         7.803843       -74.7981
23                    9            5.25         7.803843       -74.7214
24                    9            3.00         7.244228       -74.6919
25                    9            5.25         7.326466       -74.6090
26                   16           10.00         7.851661       -74.4027
27                    4            3.00         7.081709       -74.6296
28                   16            7.00         7.753624       -74.6857
29                   16           11.00         7.630461       -74.7294
...                 ...             ...              ...            ...
17354                 9            9.00         7.426549       -74.6888
17355                25           22.50         8.486734       -74.5157
17356                 4            3.00         6.845880       -74.7025
17357                 9            9.75         7.455877       -74.7316
17358                 9            9.00         7.930206       -74.3676
17359                 9            9.00         7.930206       -74.3676
17360                 9            7.50         7.138867       -74.8219
17361                 9            7.50         7.533694       -74.7211
17362                 4            5.00         7.265430       -74.7103
17363                 9            7.50         7.326466       -74.5753
17364                 4            3.00         7.098376       -74.6994
17365                 9            7.50         7.839919       -74.6768
17366                16           14.00         8.499029       -74.4158
17367                16           11.00         7.926603       -74.7319
17368                 9            6.75         7.081709       -74.6918
17369                 4            4.50         7.333023       -74.6927
17370                25           13.75         8.188689       -74.6488
17371                16           13.00         8.134468       -74.6577
17372                16           10.00         8.044947       -74.9709
17373                16           12.00         8.291547       -74.3603
17374                25           18.75         8.405144       -74.5679
17375                 9            7.50         7.261927       -74.6217
17376                 9            5.25         7.313220       -74.6925
17377                 9            7.50         7.727535       -74.3421
17378                 9            6.00         7.306531       -74.7181
17379                16           14.00         8.163371       -74.8443
17380                 9            7.50         7.177782       -74.8317
17381                 9            7.50         7.333023       -74.6467
17382                 9            7.50         7.377759       -74.5345
17383                 4            1.50         6.927558       -74.7049

[17384 rows x 4 columns]

In [11]:
test_data[['bedrooms_squared', 'bed_bath_rooms', 'log_sqft_living', 'lat_plus_long']]

      bedrooms_squared  bed_bath_rooms  log_sqft_living  lat_plus_long
0                    9            3.00         7.265430       -74.4732
1                   16           12.00         7.989560       -74.8036
2                    9            6.00         7.444249       -74.9132
3                    9            7.50         7.749322       -74.5309
4                    9            3.00         6.993933       -74.6861
5                   16           10.00         7.870930       -74.6499
6                   16            9.00         8.347590       -74.9020
7                   16           10.00         7.718685       -74.7477
8                    9            5.25         7.138867       -74.8984
9                   16            8.00         7.919356       -74.5702
10                   9            5.25         7.489971       -74.7219
11                  16           10.00         7.549609       -74.6820
12                  16           10.00         7.590852       -75.0823
13                   9            5.25         7.580700       -74.9194
14                  25            8.75         7.615791       -74.4673
15                  16           10.00         8.080237       -74.9347
16                   9            6.75         7.975908       -74.4083
17                   9            6.75         7.064759       -74.7088
18                  25           12.50         7.944492       -74.5573
19                   9            3.00         6.966024       -74.6366
20                  16            4.00         7.843849       -74.7176
21                   9            3.00         7.130899       -74.9785
22                  25           11.25         7.630461       -74.8473
23                   9            6.00         7.610853       -74.5648
24                  16           10.00         7.893572       -74.5600
25                   9            5.25         7.352441       -74.8594
26                  16           10.00         8.263590       -74.5343
27                   9            7.50         7.021084       -74.6994
28                   9            7.50         7.420579       -74.8285
29                   9            7.50         7.570443       -74.7873
...                ...             ...              ...            ...
4199                16           10.00         7.903966       -74.8367
4200                 9            6.00         7.590852       -74.8296
4201                 9            9.75         7.200425       -74.6556
4202                 4            3.00         6.927558       -74.6680
4203                16           10.00         7.753624       -74.7220
4204                16           15.00         8.266164       -74.4008
4205                16           11.00         8.077137       -74.6567
4206                25           13.75         8.061487       -74.4667
4207                 4            5.50         7.901007       -74.3094
4208                 4            5.00         7.512071       -74.8311
4209                 4            4.00         7.012115       -74.8386
4210                25           17.50         8.546752       -74.4651
4211                16           11.00         7.807917       -74.6502
4212                16           14.00         8.366370       -74.3792
4213                 9            7.50         8.104703       -74.8712
4214                 9            4.50         7.056175       -74.7032
4215                 9            7.50         7.668561       -74.5370
4216                 9            7.50         7.695303       -74.9134
4217                 4            5.00         7.371489       -74.8151
4218                16           10.00         7.811973       -74.6788
4219                16           14.00         8.250620       -74.5980
4220                 9            7.50         8.034955       -75.0516
4221                16           13.00         7.549609       -74.7241
4222                 9            6.75         7.313220       -74.6965
4223                 4            2.00         6.565265       -74.6877
4224                25           18.75         8.335671       -74.6456
4225                16           11.00         7.824046       -74.7321
4226                16           10.00         7.832014       -74.6533
4227                16           10.00         7.745003       -74.8513
4228                 4            1.50         6.927558       -74.7046

[4229 rows x 4 columns]

In [12]:
train_data.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15', 'bedrooms_squared',
       'bed_bath_rooms', 'log_sqft_living', 'lat_plus_long'],
      dtype='object')

## Quiz Question: what are the mean (arithmetic average) values of your 4 new variables on TEST data? (round to 2 digits)

In [13]:
[np.mean(np.array(test_data[col])) for col in ['bedrooms_squared', 'bed_bath_rooms', 'log_sqft_living', 'lat_plus_long']]

[12.4466777015843, 7.5039016315913925, 7.550274679645938, -74.65333355403168]

In [14]:
np.mean(np.array(test_data['lat_plus_long']))

-74.65333355403168

## Fitting Multiple Linear Regression Model

Model 1: ‘sqft_living’, ‘bedrooms’, ‘bathrooms’, ‘lat’, and ‘long’
Model 2: ‘sqft_living’, ‘bedrooms’, ‘bathrooms’, ‘lat’,‘long’, and ‘bed_bath_rooms’
Model 3: ‘sqft_living’, ‘bedrooms’, ‘bathrooms’, ‘lat’,‘long’, ‘bed_bath_rooms’,
         ‘bedrooms_squared’, ‘log_sqft_living’, and ‘lat_plus_long'

In [14]:
from sklearn.linear_model import LinearRegression as LR

In [15]:
def prediction(features):
    X_train = train_data[features]
    y_train = train_data[['price']]
    
    X_test = test_data[features]
    y_test = test_data[['price']]
    
    lr = LR()
    model = lr.fit(X_train, y_train)
    
    #Predict on test set
    prediction_test = model.predict(X_test)
    
    #Predict on train data
    prediction_train = model.predict(X_train)
    
    #RMSE and R-Squared Error
    print("Test Data\nRSS:- {}\tR-Squared Error:- {}\n" .format(mean_squared_error(y_test, prediction_test) * len(y_test), r2_score(y_test, prediction_test)))
    print("Train Data\nRSS:- {}\tR-Squared Error:- {}\n" .format(mean_squared_error(y_train, prediction_train) * len(y_train), r2_score(y_train, prediction_train)))
    
    return (model, prediction_test)

## Model 1

In [16]:
model_1 = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']

In [17]:
model_one, prediction_test_model_1 = prediction(model_1)

Test Data
RSS:- 225500469795490.34	R-Squared Error:- 0.5801585583483893

Train Data
RSS:- 967879963049545.8	R-Squared Error:- 0.5926022811353866

## Model 2

In [18]:
model_2 = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long', 'bed_bath_rooms']

In [19]:
model_two, prediction_test_model_2 = prediction(model_2)

Test Data
RSS:- 223377462976467.5	R-Squared Error:- 0.5841112163820648

Train Data
RSS:- 958419635074069.9	R-Squared Error:- 0.596584299757589

## Model 3

In [20]:
model_3 = ['sqft_living', 'bedrooms', 'bathrooms', 'lat','long', 'bed_bath_rooms','bedrooms_squared', 'log_sqft_living', 'lat_plus_long']

In [21]:
model_three, prediction_test_model_3 = prediction(model_3)

Test Data
RSS:- 259236319207180.12	R-Squared Error:- 0.5173484557122805

Train Data
RSS:- 903436455050477.8	R-Squared Error:- 0.6197276883725955

## Quiz Question: What is the sign (positive or negative) for the coefficient/weight for ‘bathrooms’ in Model 1?

In [22]:
model_one.coef_
#Positive

array([[ 3.12258646e+02, -5.95865332e+04,  1.57067421e+04,
         6.58619264e+05, -3.09374351e+05]])

In [23]:
model_one.intercept_

array([-69075726.79256983])

## Quiz Question: What is the sign (positive or negative) for the coefficient/weight for ‘bathrooms’ in Model 2?

In [24]:
model_two.coef_
#Negative

array([[ 3.06610053e+02, -1.13446368e+05, -7.14613083e+04,
         6.54844630e+05, -2.94298969e+05,  2.55796520e+04]])

In [25]:
model_two.intercept_

array([-66867968.87107886])

## Quiz Question: Which model (1, 2 or 3) had the lowest RSS on TRAINING data?

In [26]:
model_three.coef_

array([[ 5.29422820e+02,  3.45142296e+04,  6.70607813e+04,
         5.34085611e+05, -4.06750711e+05, -8.57050439e+03,
        -6.78858667e+03, -5.61831484e+05,  1.27334900e+05]])

In [27]:
model_three.intercept_

array([-62036084.9860983])

## Quiz Question: Which model (1, 2, or 3) had the lowest RSS on TESTING data?

### Model 1

### Model 2

In [79]:
#Lowest RSS on test data

### Model 3

In [80]:
#Lowest RSS on train data